-- Disable RLS on all application tables.
-- The backend handles authorization via CurrentUser extractor + role guards.
-- RLS was causing issues with Supabase connection pooler using non-superuser roles.

ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE driver_edits DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_service DISABLE ROW LEVEL SECURITY;
ALTER TABLE trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_handovers DISABLE ROW LEVEL SECURITY;
ALTER TABLE advances DISABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE salaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE broadcasts DISABLE ROW LEVEL SECURITY;
ALTER TABLE owners DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE platforms DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_platform_earnings DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_counters DISABLE ROW LEVEL SECURITY;
ALTER TABLE config_expense_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE config_leave_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE config_document_types DISABLE ROW LEVEL SECURITY;
